### ISSUE TITLE
Ch 3: code for update_bandit is missing

### ISSUE THREAD

**Issue by faisito** [unbalancedparentheses/data_science_in_julia_for_hackers#112]
the code for the function update_bandit is not being displayed (missing)

**Comment by salbert83** [comment]
I suggest the following implementation, along with a few minor modifications:

using Distributions
using Plots
using Random
using StatsPlots

mutable struct beta_bandit
    p::Float64
    d::Beta{Float64}
    beta_bandit(p=p, d=Beta(1,1)) = new(p, d)
end

sample_bandit(bandit::beta_bandit) = rand(bandit.d)

pull_arm(bandit::beta_bandit) = bandit.p > rand()

function update_bandit!(bandit::beta_bandit, r)
    α, β = bandit.d.α, bandit.d.β
    if r
        bandit.d = Beta(α + 1, β)
    else
        bandit.d = Beta(α, β + 1)
    end
end

function beta_bandit_experiment(band_probs, trials)
    bandits = [beta_bandit(p) for p ∈ band_probs]
    reward = 0
    for i = 1:trials
        shuffled = shuffle(bandits)
        mxidx = argmax([sample_bandit(bandit) for bandit ∈ shuffled])
        best_bandit = shuffled[mxidx]
        r = pull_arm(best_bandit)
        if r
            reward += 1
        end
        update_bandit!(best_bandit, r)
    end

    plt = plot()
    for bandit ∈ bandits
        plot!(plt, bandit.d
        , xlim=(0,1)
        , lw = 2
        , xlabel = "Success probability of bandit"
        , ylabel = "Probability density")
    end

    return reward, bandits, plt

end

BANDIT_PROBABILITIES = [0.3, 0.5, 0.75]
N_TRIALS = 100
rew, bandits, bandit_plot = beta_bandit_experiment(BANDIT_PROBABILITIES, N_TRIALS)
display(bandit_plot)

**Comment by pefontana** [comment]
Thank you very much for the contributions!
@faisito We will load a new HTML file where the update_bandit function isn't hidden, in the meanwhile you can open the .jl file using a Pluto notebook and see the function.

@salbert83 We will really take into account your code reformulation and try to implement it in the notebook
