### ISSUE TITLE
Visualization of code in Chapter 5

### ISSUE THREAD

**Issue by facusapienza21** [unbalancedparentheses/data_science_in_julia_for_hackers#121]
Hi! The [html version](https://datasciencejuliahackers.com/05_prob_prog_intro.jl.html) of chapter 5 about Probabilistic Programming displays the code in such a way that the last line is no visible. I had checked with the other chapters and I just have this problem with chapter 5. I can see the missing lines from the source code.

**Comment by pefontana** [comment]
Hi @facusapienza21 !
We know that there is a problem with the html version of chapter 5. We will solve it in the next few days.
By the time, if you want to read the chapter you can download the GitHub repo and open the /05_prob_prog_intro/05_prob_prog_intro.jl  file using Pluto.
Thank you!

**Comment by facusapienza21** [comment]
Thank you @pefontana , that is exactly what I was doing. Really appreciated all the work you are doing with the book, I am really enjoyingn it!

**Comment by unbalancedparentheses** [comment]
@facusapienza21 thanks for creating the issue. we really appreciate your feedback!

**Comment by pefontana** [comment]
We just migrate the book to a bookdown R version!
Now you can see chapter 5 in the html version
